package org.blog.entity;

import java.util.Date;

public class SysLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.id
     *
     * @mbggenerated Mon Aug 20 13:19:17 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.ip
     *
     * @mbggenerated Mon Aug 20 13:19:17 CST 2018
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.create_by
     *
     * @mbggenerated Mon Aug 20 13:19:17 CST 2018
     */
    private Date createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.remark
     *
     * @mbggenerated Mon Aug 20 13:19:17 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.operate_url
     *
     * @mbggenerated Mon Aug 20 13:19:17 CST 2018
     */
    private String operateUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.operate_by
     *
     * @mbggenerated Mon Aug 20 13:19:17 CST 2018
     */
    private String operateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.id
     *
     * @return the value of sys_log.id
     *
     * @mbggenerated Mon Aug 20 13:19:17 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.id
     *
     * @param id the value for sys_log.id
     *
     * @mbggenerated Mon Aug 20 13:19:17 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.ip
     *
     * @return the value of sys_log.ip
     *
     * @mbggenerated Mon Aug 20 13:19:17 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.ip
     *
     * @param ip the value for sys_log.ip
     *
     * @mbggenerated Mon Aug 20 13:19:17 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.create_by
     *
     * @return the value of sys_log.create_by
     *
     * @mbggenerated Mon Aug 20 13:19:17 CST 2018
     */
    public Date getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.create_by
     *
     * @param createBy the value for sys_log.create_by
     *
     * @mbggenerated Mon Aug 20 13:19:17 CST 2018
     */
    public void setCreateBy(Date createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.remark
     *
     * @return the value of sys_log.remark
     *
     * @mbggenerated Mon Aug 20 13:19:17 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.remark
     *
     * @param remark the value for sys_log.remark
     *
     * @mbggenerated Mon Aug 20 13:19:17 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.operate_url
     *
     * @return the value of sys_log.operate_url
     *
     * @mbggenerated Mon Aug 20 13:19:17 CST 2018
     */
    public String getOperateUrl() {
        return operateUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.operate_url
     *
     * @param operateUrl the value for sys_log.operate_url
     *
     * @mbggenerated Mon Aug 20 13:19:17 CST 2018
     */
    public void setOperateUrl(String operateUrl) {
        this.operateUrl = operateUrl == null ? null : operateUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.operate_by
     *
     * @return the value of sys_log.operate_by
     *
     * @mbggenerated Mon Aug 20 13:19:17 CST 2018
     */
    public String getOperateBy() {
        return operateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.operate_by
     *
     * @param operateBy the value for sys_log.operate_by
     *
     * @mbggenerated Mon Aug 20 13:19:17 CST 2018
     */
    public void setOperateBy(String operateBy) {
        this.operateBy = operateBy == null ? null : operateBy.trim();
    }
}